
export const DELETECITY = 'DELETECITY';
export const UPDATECITY = 'UPDATECITY';
export const UPDATELOCATION = 'UPDATELOCATION';
export const UPDATETOSELECTED = 'UPDATESTATE';
export const UPDATETOUNSELECTED = 'UPDATETOUNSELECTED';
export const UPDATECITIES = 'UPDATECITIES';
export const ADDCOMMENT = 'ADDCOMMENT';
export const UPDATEITEMLIKENUM = 'UPDATAITEMLIKENUM';
export const UPDATELIKENUM = 'UPDATELIKENUM';
export const DELETECOMMENT = 'DELECOMMENT';
export const ADDTRANSMITNUM = 'ADDTRANSMITNUM';
export const ADDREPLY = 'ADDREPLY';