
export const ADDCITY = 'ADDCITY';
export const DELETECITY = 'DELETECITY';
export const UPDATECITY = 'UPDATECITY';
export const UPDATELOCATION = 'UPDATELOCATION';
export const UPDATETOSELECTED = 'UPDATESTATE';
export const UPDATETOUNSELECTED = 'UPDATETOUNSELECTED';